linters-settings:
  godox:
    keywords: # default keywords are TODO, BUG, and FIXME, but we override this by ignoring TODO
      - BUG
      - FIXME
  funlen:
    lines: 100
    statements: 80

issues:
  exclude-use-default: false
  exclude:
    - Using the variable on range scope `tt` in function literal
    - GetJsonSHA256Fingerprints should be GetJSONSHA256Fingerprints
    - ST1003  # CamelCase variables; see constants/cipher.go

linters:
  enable-all: true
  disable:
    - dupl              # Tool for code clone detection [fast: true, auto-fix: false]
    - gochecknoglobals  # Checks that no globals are present in Go code [fast: true, auto-fix: false]
    - gochecknoinits    # Checks that no init functions are present in Go code [fast: true, auto-fix: false]
    - golint            # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: true, auto-fix: false]
    - goerr113          # Golang linter to check the errors handling expressions [fast: true, auto-fix: false]
    - gomnd             # An analyzer to detect magic numbers. [fast: true, auto-fix: false]
    - lll               # Reports long lines [fast: true, auto-fix: false]
    - testpackage       # Makes you use a separate _test package [fast: true, auto-fix: false]
    - wsl               # Whitespace Linter - Forces you to use empty lines! [fast: true, auto-fix: false]
    - gofumpt           # Enforce a stricter format than gofmt
    - gci               # Enforce blank lines check
    - nlreturn          # Enforce blank lines for return statements
    - exhaustivestruct  # Enforce structures to be fully filled on instantiation - terrible with openpgp configs
