linters-settings:
  godox:
    keywords: # default keywords are TODO, BUG, and FIXME, but we override this by ignoring TODO
      - BUG
      - FIXME
  funlen:
    lines: 100
    statements: 80

issues:
  exclude-use-default: false
  exclude:
    - Using the variable on range scope `tt` in function literal

linters:
  enable-all: true
  disable:
    - dupl              # Tool for code clone detection [fast: true, auto-fix: false]
    - gochecknoglobals  # Checks that no globals are present in Go code [fast: true, auto-fix: false]
    - gochecknoinits    # Checks that no init functions are present in Go code [fast: true, auto-fix: false]
    - golint            # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: true, auto-fix: false]
    - gomnd             # An analyzer to detect magic numbers. [fast: true, auto-fix: false]
    - stylecheck        # Stylecheck is a replacement for golint [fast: true, auto-fix: false]
    - wsl               # Whitespace Linter - Forces you to use empty lines! [fast: true, auto-fix: false]
    - lll               # Reports long lines [fast: true, auto-fix: false]\

